### ISSUE TITLE
Spec text reviewer signoff?

### ISSUE THREAD

**Issue by ljharb** [ljharb/proposal-string-pad-left-right#11]
It appears that all the outstanding issues with this proposal's spec text have been resolved.

@littledan @michaelficarra - as the designated reviewers (thanks for volunteering!), are there any other issues blocking official signoff? If so, please file them! If not, please indicate as such here :-)

Thanks!

**Comment by littledan** [comment]
You have my signoff.

**Comment by michaelficarra** [comment]
A few notes on the current spec text:
1. "number of elements in S" would be better as simply "length of S". You can assert it's a string first, but it should be obvious, as ToString is used frequently.
2. The description "a string consisting of a single space" should list the unicode code point.
3. "If intMaxLength is not greater than stringLength, return S." Should put the return value first, followed by the condition. "Return S if ...".
4. The names `fillStr` and `fillString` can be easily confused.
5. "... the {first,last} fillLen elements of stringFiller ...". I think this new value should be pulled out and named.
6. We could just eliminate step 13 and make 14 simpler by appending `fillStr` to itself.

Which stage are you targeting for the next committee meeting?

**Comment by ljharb** [comment]
@michaelficarra thanks for the feedback!

1) I see "length of" used a few times in the spec, but `slice`, `split`, `startsWith`, etc have "number of elements in S" - I wanted to be consistent with other string methods. @allenwb/@bterlson, is there a reason to prefer one over the other?

2) The spec mentions code units without describing unicode chars, like "g" for regex flags. Can you point to an existing example where a literal JS string value has unicode data?

3) Can you show me an example of where this occurs? The spec seems to universally state the "if" before the "return".

4) Good point - I could just name `fillStr` as `F`, to avoid the overlap?

5) What's the benefit of pulling it out and naming it? I'm happy to do it, but it seems like it adds complication for no readability enhancement.

6) I don't see how - since strings are immutable, we have to create a new string every time, and we always have to keep an original `fillStr` around for each concatenation iteration - if we change the value of `fillStr`, we can't append it as a single unit anymore. How would you propose combining these steps?

I'm hoping to target stage 3.

**Comment by michaelficarra** [comment]
1. Okay, I was just suggesting "length of" because that's what I saw elsewhere, but whichever way is most consistent. If we have no consistency now, I would recommend we use "length of" for values known to be strings.
2. Pretty much everywhere a particular code point is mentioned (as you have done here with space), the code point is described as "U+0000 (NULL)". Search the spec for "U+" and you'll see.
3. Okay, you're right. There's 31 occurrences of "return ... if ..." and 828 occurrences of "if ... return ...". I must have by chance been looking at some of the former.
4. Sure, whatever you prefer.
5. It makes it easier for me to read, and easier to reference when talking about the spec.
6. Try it out. Appending to itself doubles its size until it exceeds the target length. You don't need the original.

**Comment by ljharb** [comment]
@michaelficarra thanks for explaining! I've made the changes you requested.

I'll leave number 1 as-is, since I think it's better to have consistency with other String methods for now, and to make the spec self-consistent as a separate PR to it.

**Comment by michaelficarra** [comment]
LGTM. :+1:

**Comment by michaelficarra** [comment]
By the way, I just wanted to point out something I noticed but which I don't think is a blocker. Using the algorithm in the specification, `F` can exceed the maximum length of a string before being sliced to an appropriate size. Say your `fillString` has length 2<sup>52</sup>+1, your _this value_ has length 1, and your `maxLength` is 2<sup>52</sup>+3. You can account for this with an algorithm that tracks the necessary remaining filler to append (to itself), but I'm not sure it's worth it. It'd be irresponsible not to bring this up with the committee, so if you think they will complain about it, you should probably fix it.

**Comment by ljharb** [comment]
Hmm, interesting point. It's worth noting that [String#repeat](http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.repeat) suffers from the same problem, but doesn't handle this case at all.

Safari throws an "out of memory" error, Firefox throws a RangeError "repeat count must be less than infinity and not overflow maximum string size", Chrome throws a RangeError "Invalid count value" (lol @ inaccurate error message)…

However, the caller in these scenarios can easily determine that this is possible by multiplying the string length by the repeat count. With padLeft/padRight, the caller can use the same method to determine that the final string length is valid, and the algorithm could still cause a problem.

Based on that, I'd say that the proposal should handle it - I'm not sure what the simplest way to do so would be yet.

**Comment by ljharb** [comment]
With #12, I think all of @michaelficarra's concerns are addressed - if so, would you be so kind as to officially sign off? :-)

**Comment by michaelficarra** [comment]
:ribbon: :+1:
