### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by anba** [ljharb/proposal-string-pad-left-right#7]
http://ljharb.github.io/proposal-string-pad-left-right/#String.prototype.padLeft
http://ljharb.github.io/proposal-string-pad-left-right/#String.prototype.padRight

Step 2 can be removed, abrupt completions are also handled in step 4.

Steps 10-11 (`ToLength(maxLength)`) should be placed before steps 6-8 (`ToString(fillString)`) to ensure the arguments are processed in the usual left to right order. 

https://github.com/ljharb/proposal-string-pad-left-right/blob/master/polyfill.js

Nit: ToLength function does not handle NaN correctly.

**Comment by ljharb** [comment]
Thanks for the thorough review!

> Step 2 can be removed, abrupt completions are also handled in step 4.

This was added due to @rwaldron filing #1. However, I think I am convinced that there isn't an observable difference here, and the step can be removed. @rwaldron, can you weigh in?

> Steps 10-11 (ToLength(maxLength)) should be placed before steps 6-8 (ToString(fillString)) to ensure the arguments are processed in the usual left to right order.

Good call! I'll rearrange the steps to follow left-to-right order, that makes perfect sense.

> Nit: ToLength function does not handle NaN correctly.

Oops, fixed, thanks :-)

**Comment by ljharb** [comment]
Reopening pending a decision on removing step 2.

**Comment by ljharb** [comment]
@bterlson: what do you think about the `ReturnIfAbrupt` in step 2? Is it necessary?

**Comment by bterlson** [comment]
It's unnecessary in the sense that it's nonobservable as ToObject passes through any abrupt completions.

**Comment by ljharb** [comment]
OK - I'll remove it then and revert #1.
