### ISSUE TITLE
Wording for optional arguments

### ISSUE THREAD

**Issue by littledan** [ljharb/proposal-string-pad-left-right#8]
The ES2015 spec tends to give optional arguments default values with phrases like "if _x_ is _undefined_, let _x_ be foo". For example, see the treatment of endPosition in String.prototype.endsWith http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.endswith

**Comment by ljharb** [comment]
Where are you seeing different wording here? I have "If _fillString_ is _undefined_, let _fillStr_ be the empty String." in both functions' spec steps.

**Comment by littledan** [comment]
Well, it should be in a numbered item in the algorithm.

**Comment by ljharb** [comment]
It already is - see step 9 in both algorithms.
