### ISSUE TITLE
Length should not be in a note

### ISSUE THREAD

**Issue by littledan** [ljharb/proposal-string-pad-left-right#9]
In this case, you don't need to say anything. If you want to write the length explicitly, it should be in normative text.

**Comment by ljharb** [comment]
Same as https://github.com/ljharb/proposal-object-values-entries/issues/7 - implementations do often mess this up, and I'd prefer to be explicit.

**Comment by littledan** [comment]
SGTM, important thing is that it's not in a note because this is normative.
